// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_Gestion_de_Importaciones.Data;

#nullable disable

namespace Sistema_de_Gestion_de_Importaciones.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250212153044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Barco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Escotilla1")
                        .HasColumnType("int")
                        .HasColumnName("escotilla1");

                    b.Property<int?>("Escotilla2")
                        .HasColumnType("int")
                        .HasColumnName("escotilla2");

                    b.Property<int?>("Escotilla3")
                        .HasColumnType("int")
                        .HasColumnName("escotilla3");

                    b.Property<int?>("Escotilla4")
                        .HasColumnType("int")
                        .HasColumnName("escotilla4");

                    b.Property<int?>("Escotilla5")
                        .HasColumnType("int")
                        .HasColumnName("escotilla5");

                    b.Property<int?>("Escotilla6")
                        .HasColumnType("int")
                        .HasColumnName("escotilla6");

                    b.Property<int?>("Escotilla7")
                        .HasColumnType("int")
                        .HasColumnName("escotilla7");

                    b.Property<string>("NombreBarco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreBarco");

                    b.HasKey("Id");

                    b.ToTable("barcos", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Bodega", b =>
                {
                    b.Property<int>("IdBodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("NombreBodega")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("bodega");

                    b.HasKey("IdBodega");

                    b.ToTable("bodegas", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombreempresa");

                    b.HasKey("IdEmpresa");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Importacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechahora");

                    b.Property<DateTime>("FechaHoraSystema")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechahorasystema");

                    b.Property<int>("IdBarco")
                        .HasColumnType("int")
                        .HasColumnName("idbarco");

                    b.Property<int>("TotalCargaKilos")
                        .HasColumnType("int")
                        .HasColumnName("totalcargakilos");

                    b.HasKey("Id");

                    b.HasIndex("IdBarco");

                    b.ToTable("importaciones", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Bodega")
                        .HasColumnType("int")
                        .HasColumnName("bodega");

                    b.Property<int>("CantidadCamiones")
                        .HasColumnType("int")
                        .HasColumnName("cantidadcamiones");

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int")
                        .HasColumnName("cantidadentregada");

                    b.Property<int>("CantidadRequerida")
                        .HasColumnType("int")
                        .HasColumnName("cantidadrequerida");

                    b.Property<int>("Escotilla")
                        .HasColumnType("int")
                        .HasColumnName("escotilla");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechahora");

                    b.Property<DateTime>("FechaHoraSystema")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechahorasystema");

                    b.Property<int>("Guia")
                        .HasColumnType("int")
                        .HasColumnName("guia");

                    b.Property<int>("GuiaAlterna")
                        .HasColumnType("int")
                        .HasColumnName("guiaalterna");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("idempresa");

                    b.Property<int>("IdImportacion")
                        .HasColumnType("int")
                        .HasColumnName("idimportacion");

                    b.Property<int>("Placa")
                        .HasColumnType("int")
                        .HasColumnName("placa");

                    b.Property<int>("PlacaAlterna")
                        .HasColumnType("int")
                        .HasColumnName("placaalterna");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("int")
                        .HasColumnName("tipotransaccion");

                    b.Property<int>("TotalCarga")
                        .HasColumnType("int")
                        .HasColumnName("totalcarga");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdImportacion");

                    b.ToTable("movimientos", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Importacion", b =>
                {
                    b.HasOne("Sistema_de_Gestion_de_Importaciones.Models.Barco", "Barco")
                        .WithMany()
                        .HasForeignKey("IdBarco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barco");
                });

            modelBuilder.Entity("Sistema_de_Gestion_de_Importaciones.Models.Movimiento", b =>
                {
                    b.HasOne("Sistema_de_Gestion_de_Importaciones.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sistema_de_Gestion_de_Importaciones.Models.Importacion", "Importacion")
                        .WithMany()
                        .HasForeignKey("IdImportacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Importacion");
                });
#pragma warning restore 612, 618
        }
    }
}
